### ISSUE TITLE
Add outrigger instructions to README.md

### ISSUE THREAD

**Issue by illepic** [phase2/particle#200]
For now, let's add a sub head about getting Particle to work with Outrigger. The following needs to be added to the outrigger project's `build.yml`:

```yml
  # Container to get Particle compiled, running, and watched from inside the theme folder in one step.
  # Usage: rig project theme
  # You can also pass any argument the gulp command within the theme accepts as an argument here.
  theme:
    extends:
      service: operational
    labels:
      com.dnsdock.name: theme
      com.dnsdock.image: [YOUR_DNSDOCK_IMAGE_NAME]
      outrigger.project: [YOUR_PROJECT_NAME]
    working_dir: /var/www/src/themes/particle
    entrypoint: [ "/init", "npm install && npm rebuild && npm run setup && npm start" ]
    ports:
    - "8080:8080"
    - "35729:35729"
```

Then run:

```sh
rig project theme
```

And navigate to [http://theme.YOUR_PROJECT_NAME.vm:8080/pl/](http://theme.YOUR_PROJECT_NAME.vm:8080/pl/).

**Comment by grayside** [comment]
Note that this is a good apples to apple slice transition, but one of the reasons the existing implementation targets gulp directly was the detail that you could also do things like run `rig project theme party` as a proxy for `gulp party`.

I'd  generally recommend the "one-time/rare-time" stuff be in a separate rig project script, rather than bake it into the service, thus limiting the versatility of the service.

build.yml
```yaml
  # Container to get Particle compiled, running, and watched from inside the theme folder in one step.
  # Usage: rig project theme
  # You can also pass any argument the gulp command within the theme accepts as an argument here.
  theme:
    extends:
      service: operational
    labels:
      com.dnsdock.name: theme
      com.dnsdock.image: [YOUR_DNSDOCK_IMAGE_NAME]
      outrigger.project: [YOUR_PROJECT_NAME]
    working_dir: /var/www/src/themes/particle
    entrypoint: [ "/init" ]
    command: "npm"
    ports:
    - "8080:8080"
    - "35729:35729"
```

outrigger.yml bits.
```yaml
<earlier bits of outrigger.yml...>
scripts:
  theme:
    name: Theme Operations via npm
    description: Frontending.
    steps:
      - docker-compose -f build.yml run --rm theme npm

  theme-setup:
    name: Theme Setup
    description: We will frontend.
    steps:
      - docker-compose -f build.yml run --rm theme "npm install && npm rebuild && npm run setup"
      - rig project theme start
```

This means you can run `rig project theme` as the equivalent of running `npm` in the theme directory. The `command` key from the build.yml is replaced with the optional argument after the service name `theme`. rig project scripts automatically append additional arguments to the end of the last step, so `rig project run:theme-setup`'s second step will result in running `npm start` in the theme directory.

Of course, if you don't like this, just moving your original bits of entrypoint after /init to the command property I just explained would help, because you could override with whatever CLI option you'd like to run in the theme, in that universe, you would do stuff like:

```
docker-compose -f build.yml run --rm theme "ls -lR"
```
