### ISSUE TITLE
apps/drupal/particle.libraries.yml needs lots of work

### ISSUE THREAD

**Issue by illepic** [phase2/particle#259]
Currently apps/drupal/particle.libraries.yml looks like this:

```yml
# @TODO: THIS IS NEEDS LOTS OF WORK, THESE PATHS MAY BE NO LONGER CORRECT
core:
  css:
    theme:
      ../../dist/assets/app-drupal.styles.css:
        preprocess: true
  js:
    ../../dist/assets/commons.js:
      preprocess: true
    ../../dist/assets/app-drupal.js:
      preprocess: true
  # see all in Drupal's `core/core.libraries.yml`
  dependencies:
    # - patternlab/j-dash
    - core/drupal
# @TODO: GET THESE PULLED OUT VIA WEBPACK
#jquery:
#  js:
#    ../node_modules/jquery/dist/jquery.min.js: { minified: true, weight: -20 }
#lodash:
#  js:
#    ../node_modules/lodash/lodash.min.js: { minified: true, weight: -20 }
```

This needs to be revamped to:

1. Remove mention of commons.js
1. Use webpack to extract jquery and lodash to their own standalone files and referenced in the `dependencies` key to override core jquery and underscore.

Info: https://www.drupal.org/node/2497313
