### ISSUE TITLE
CSS-Background-Images not working in compiled patternlab

### ISSUE THREAD

**Issue by joehae** [phase2/particle#265]
Background-images are not visible when i compile my files (`yarn compile:pl`). Am I missing something? 

### Example:
```scss
.some-class {
  background: url("icons/some-icon.svg") no-repeat center;
}
```
This works fine with the generated patternlab on my local machine. I can only get this to work with the compiled version when I change the `publicPath` in  **webpack.shared.config.js** to `'./'` though.
