### ISSUE TITLE
Grav Theme: Update Gulp Task for Twig Namespaces

### ISSUE THREAD

**Issue by jryanconklin** [phase2/particle#279]
Currently the twig namespaces are generated for the `apps/grav/twig-namespaces.yaml` file from the gulp task for twig namespaces, specifically:

```
        // The twig-namespaces plugin wants to know about our namespaces
        configFile: path.join(PATH_GRAV, 'twig-namespaces.yaml'),
        atKey: 'generated-namespaces',
        pathRelativeToDir: path.join(PATH_GRAV, ''),
```

This creates our list of generated namespaces as:

```
generated-namespaces:
  protons:
    paths:
      - ../../source/_patterns/00-protons
```

The twig-namespaces plugin however needs this in a different format, namely:

```
namespaces:
  protons:
    paths:
      - user/themes/particle/source/_patterns/00-protons
```

If possible, we should update the gulp task to update the generated paths as required by twig-namespaces plugin, namely `../../source/` => `user/themes/particle/source/`. Once this is done we can update the task to apply the atKey to namespaces and add the `twig-namespaces.yaml` file to `.gitignore`.
